"""Demo mode for the gcp-cspace platform — a simulated vulnerable Confidential
Space deployment. No GCP credentials or live token required.

The findings are generated by running the real analysis functions over
synthetic-but-realistic inputs, so the demo output tracks the actual check
logic rather than hand-written strings.
"""

from __future__ import annotations

from ...checks.base import Finding, Severity, Status, Target
from ...probes import ObjectStoreSurface, probe_surface
from .attestation import analyze_token_claims
from .gcs_bootstrap import analyze_gcs_bucket
from .image_signing import analyze_image_signing
from .keybind import analyze_wif_condition
from .kms_binding import analyze_kms_bindings
from .metadata_mutability import analyze_metadata_writers
from .sa_identity import analyze_sa_impersonation, analyze_sa_keys
from .vm_config import analyze_instance_config
from .wif_siblings import analyze_providers

# A WIF provider condition that only proves *identity* — it checks the workload
# service account and that it is Confidential Space, but never pins the image
# digest and never requires dbgstat. This is the deploy-time bug.
_DEMO_CONDITION = (
    "assertion.swname == 'CONFIDENTIAL_SPACE' && "
    "assertion.google_service_accounts.exists(sa, sa == "
    "'workload@demo-proj.iam.gserviceaccount.com')"
)

# KMS key grants decrypt to allAuthenticatedUsers and a plain service account —
# neither requires an attestation token.
_DEMO_KMS_BINDINGS = [
    {"role": "roles/cloudkms.cryptoKeyDecrypter", "members": ["allAuthenticatedUsers"]},
    {
        "role": "roles/cloudkms.cryptoKeyEncrypterDecrypter",
        "members": ["serviceAccount:workload@demo-proj.iam.gserviceaccount.com"],
    },
]

# Bootstrap bucket: public access not enforced, fine-grained ACLs, world-writable,
# no versioning, no retention.
_DEMO_BUCKET_META = {
    "iamConfiguration": {
        "publicAccessPrevention": "inherited",
        "uniformBucketLevelAccess": {"enabled": False},
    },
    "versioning": {"enabled": False},
}
_DEMO_BUCKET_BINDINGS = [
    {"role": "roles/storage.objectAdmin", "members": ["allUsers"]},
]

# VM: confidential compute off, plain type, shielded boot disabled.
_DEMO_INSTANCE = {
    "confidentialInstanceConfig": {
        "enableConfidentialCompute": False,
        "confidentialInstanceType": "",
    },
    "shieldedInstanceConfig": {
        "enableSecureBoot": False,
        "enableVtpm": False,
        "enableIntegrityMonitoring": False,
    },
}

# A debug-mode token from a USABLE (debug-tooling) image, unsigned.
_DEMO_CLAIMS = {
    "dbgstat": "enabled",
    "hwmodel": "GCP_AMD_SEV",
    "submods": {
        "container": {
            "image_reference": "us-docker.pkg.dev/demo-proj/repo/workload:latest",
            "image_digest": "sha256:" + "0" * 64,
            "image_signatures": [],
        },
        "confidential_space": {"support_attributes": ["USABLE"]},
    },
}


def run_gcp_cspace_demo() -> tuple[Target, list[Finding]]:
    target = Target(
        platform="gcp-cspace",
        gcp_project="demo-proj",
        wip_provider=(
            "projects/123456789/locations/global/workloadIdentityPools/"
            "workload-pool/providers/workload-provider"
        ),
        gcp_kms_key=("projects/demo-proj/locations/global/keyRings/workload/cryptoKeys/state-key"),
        gcs_bucket="workload-state-demo-proj",
        gcp_instance="workload-vm",
        gcp_zone="us-central1-a",
    )

    kb = analyze_wif_condition(_DEMO_CONDITION)
    reasons = "; ".join(kb["gating_weaknesses"])
    if kb["recommended_weaknesses"]:
        reasons += ". Additionally, it " + "; ".join(kb["recommended_weaknesses"])

    kms = analyze_kms_bindings(_DEMO_KMS_BINDINGS)
    kms_members = ", ".join(f"{g['member']} ({g['role']})" for g in kms["weak_grants"])
    gcs = analyze_gcs_bucket(_DEMO_BUCKET_META, _DEMO_BUCKET_BINDINGS)
    vm = analyze_instance_config(_DEMO_INSTANCE)
    att = analyze_token_claims(_DEMO_CLAIMS)

    # Simulate a wide-open bucket: every injection-shaped canary write is accepted.
    probe = probe_surface(ObjectStoreSurface(put_fn=lambda name: None)).as_evidence()

    # --- Tier-1 bypass inputs (synthetic-but-realistic) ---
    _WORKLOAD_SA = "workload-sa@demo-proj.iam.gserviceaccount.com"
    meta = analyze_metadata_writers(
        [{"role": "roles/compute.instanceAdmin.v1", "members": [f"serviceAccount:{_WORKLOAD_SA}"]}],
        workload_sa=_WORKLOAD_SA,
    )
    imp = analyze_sa_impersonation(
        [{"role": "roles/iam.serviceAccountTokenCreator", "members": ["allAuthenticatedUsers"]}]
    )
    keys = analyze_sa_keys(
        [{"keyType": "USER_MANAGED", "name": "keys/abc", "validAfterTime": "2026-01-01T00:00:00Z"}]
    )
    sib = analyze_providers(
        [
            {
                "name": ".../providers/workload-provider",
                "attributeCondition": _DEMO_CONDITION,
                "oidc": {"issuerUri": "https://confidentialcomputing.googleapis.com/"},
            },
            {
                "name": ".../providers/legacy-ci",
                "attributeCondition": None,
                "oidc": {"issuerUri": "https://token.actions.githubusercontent.com"},
            },
        ],
        primary_provider_id="workload-provider",
    )
    imgsign = analyze_image_signing(
        [
            {
                "key": "tee-image-reference",
                "value": "us-docker.pkg.dev/demo-proj/repo/workload:latest",
            }
        ],
        [{"role": "roles/artifactregistry.writer", "members": ["allAuthenticatedUsers"]}],
    )

    findings = [
        Finding(
            check_id="CSPACE-KEYBIND-01",
            title="Confidential Space key release binds to a code measurement",
            status=Status.FAIL,
            severity=Severity.HIGH,
            summary=(
                f"WIF provider condition does not bind key release to a code "
                f"measurement: it {reasons}."
            ),
            remediation=(
                "Pin assertion.submods.container.image_digest to your CI-built "
                "image and require assertion.dbgstat == 'disabled-since-boot' in "
                "the WIF provider attribute condition."
            ),
            evidence=kb,
        ),
        Finding(
            check_id="CSPACE-KMS-01",
            title="Cloud KMS decrypt is federated through the attested pool",
            status=Status.FAIL,
            severity=Severity.CRITICAL,
            summary=(
                f"{len(kms['weak_grants'])} decrypt grant(s) are not federated "
                f"through a Workload Identity pool: {kms_members}. Access does not "
                f"require an attestation token."
            ),
            remediation=(
                "Grant KMS decrypt only to a principalSet:// member scoped to the "
                "Confidential Space workload identity pool; remove "
                "allAuthenticatedUsers and plain service-account grants."
            ),
            evidence=kms,
        ),
        Finding(
            check_id="GCS-BOOT-01",
            title="Bootstrap-state bucket hardening",
            status=Status.FAIL,
            severity=Severity.CRITICAL,
            summary="Bootstrap bucket is not hardened: " + "; ".join(gcs["issues"]) + ".",
            remediation=(
                "Enforce publicAccessPrevention, enable uniformBucketLevelAccess, "
                "scope object-write to the workload identity, enable versioning, "
                "and add a retention policy."
            ),
            evidence=gcs,
        ),
        Finding(
            check_id="GCS-BOOT-02",
            title="Bootstrap bucket rejects injection-shaped object writes",
            status=Status.FAIL,
            severity=Severity.HIGH,
            summary=(
                f"State bucket accepted {len(probe['vulnerable'])}/{probe['tested']} "
                f"injection-shaped object writes across classes: "
                f"{', '.join(probe['vulnerable_classes'])}. A bootstrap consumer that "
                f"joins these names onto a local path without sanitizing gets "
                f"arbitrary file write (boot-time RCE — the FB-09 class)."
            ),
            remediation=(
                "Scope object-write to the attested workload identity and sanitize "
                "downloaded object names enclave-side (reject normalized paths that "
                "escape the state dir; refuse absolute paths; decode once and re-check)."
            ),
            evidence=probe,
        ),
        Finding(
            check_id="CSPACE-VM-01",
            title="Confidential VM runs SEV-SNP with Shielded boot",
            status=Status.FAIL,
            severity=Severity.HIGH,
            summary="Confidential VM posture is incomplete: " + "; ".join(vm["issues"]) + ".",
            remediation=(
                "Recreate the instance with confidentialInstanceType=SEV_SNP, "
                "enableConfidentialCompute=true, and Shielded VM enabled."
            ),
            evidence=vm,
        ),
        Finding(
            check_id="CSPACE-ATT-01",
            title="Confidential Space attestation token asserts a trusted state",
            status=Status.FAIL,
            severity=Severity.CRITICAL,
            summary=(
                "Attestation token does not assert a trusted state: "
                + "; ".join(att["issues"])
                + "."
            ),
            remediation=(
                "Launch from a non-debug Confidential Space image, deploy a "
                "cosign-signed workload container, and run on an AMD SEV-SNP "
                "machine type."
            ),
            evidence=att,
        ),
        Finding(
            check_id="CSPACE-META-01",
            title="Confidential VM metadata is not broadly mutable",
            status=Status.FAIL,
            severity=Severity.CRITICAL,
            summary=(
                "The workload SA can rewrite the VM's tee-image-reference/tee-cmd metadata "
                "— it can run its own code as the attested workload."
            ),
            remediation="Restrict compute.instances.setMetadata to a tight human-admin set.",
            evidence=meta,
        ),
        Finding(
            check_id="CSPACE-SA-01",
            title="Workload SA cannot be impersonated to bypass attestation",
            status=Status.FAIL,
            severity=Severity.CRITICAL,
            summary=(
                "allAuthenticatedUsers can impersonate the workload SA (tokenCreator) — "
                "mint tokens as the SA and reach KMS/GCS with no attestation."
            ),
            remediation="Remove serviceAccountTokenCreator/User grants on the workload SA.",
            evidence=imp,
        ),
        Finding(
            check_id="CSPACE-SAKEY-01",
            title="Workload SA has no long-lived user-managed keys",
            status=Status.FAIL,
            severity=Severity.HIGH,
            summary=(
                f"Workload SA has {keys['count']} user-managed key(s) — a stolen key reaches "
                f"KMS/GCS permanently, with no attestation."
            ),
            remediation="Delete user-managed keys; disable SA key creation via org policy.",
            evidence=keys,
        ),
        Finding(
            check_id="CSPACE-WIF-02",
            title="All providers in the workload identity pool bind attestation",
            status=Status.FAIL,
            severity=Severity.HIGH,
            summary=(
                f"{len(sib['weak_providers'])} of {sib['total']} pool provider(s) do not bind "
                f"Confidential Space attestation — a weaker sibling is a lateral bypass."
            ),
            remediation="Remove/scope any non-CS-issuer or unconditioned sibling provider.",
            evidence=sib,
        ),
        Finding(
            check_id="CSPACE-IMG-01",
            title="Workload image signing is enforced and the registry is not plantable",
            status=Status.FAIL,
            severity=Severity.HIGH,
            summary="Workload image trust is incomplete: " + "; ".join(imgsign["issues"]) + ".",
            remediation=(
                "Set tee-signed-image-repos, cosign-sign the image, pin by @sha256, and scope "
                "Artifact Registry write to CI only."
            ),
            evidence=imgsign,
        ),
    ]

    return target, findings
