"""Demo mode for the gpu-cc platform — a simulated vulnerable NVIDIA CC
deployment. No GPU, driver, or attestation evidence required.

The findings are generated by running the real ``analyze_*`` functions over
synthetic-but-realistic inputs, so the demo output tracks the actual check logic
rather than hand-written strings.
"""

from __future__ import annotations

from typing import Any

from ...checks.base import Finding, Severity, Status, Target
from ...probes import ObjectStoreSurface, probe_surface
from .attestation import analyze_attestation_report
from .cc_mode import analyze_cc_mode
from .cert_chain import analyze_cert_policy
from .cvm_binding import analyze_cvm_binding
from .decrypt_location import analyze_decrypt_location
from .dma_session import analyze_dma_session
from .failopen import analyze_fail_closed
from .key_hygiene import analyze_key_hygiene
from .launch_mutability import analyze_launch_mutability
from .ready_state import analyze_key_release_policy
from .reattest import analyze_reattestation
from .rim_measurement import analyze_rim_pinning
from .signature_verify import analyze_signature_verification
from .vram_encryption import analyze_vram_encryption

# A debug (DevTools) GPU with memory protection off and no confidential CPU VM.
_DEMO_REPORT: dict[str, Any] = {
    "cc_mode": "devtools",
    "gpu": {"model": "H100", "uuid": "GPU-00000000", "debug": False},
    "measurements": {"vbios": "sha384:aa", "gsp_firmware": "sha384:bb", "driver": "sha384:cc"},
    "signature": {"present": True, "verified": True},
    "memory": {"vram_encryption": False, "pcie_encryption": False, "spdm_session": False},
    "cpu_tee": {"type": "none", "verified": False, "debug": True, "secure_boot": False},
}

# A verifier that trusts a signed report but pins nothing and skips the cert chain.
_DEMO_POLICY: dict[str, Any] = {
    "verifier": "nras",
    "pinned_measurements": [],
    "cert_chain_to_nvidia_root": False,
    "revocation_check": False,
}

# Keys released before attestation, decrypted in host RAM, DEK handed in via env,
# no rotation, and a workload SA anyone can impersonate.
_DEMO_KBS: dict[str, Any] = {
    "attest_before_ready": False,
    "attestation_bound": False,
    "decrypt_location": "host",
    "dek_source": "env",
    "key_rotation_days": None,
    "sa_user_managed_keys": 1,
    "sa_impersonators": ["allAuthenticatedUsers"],
}

# Launch measurement unpinned and mutable by the untrusted host.
_DEMO_LAUNCH: dict[str, Any] = {
    "measurement_pinned": False,
    "mutable_by": [{"principal": "host-vmm", "kind": "host"}],
}


def run_gpucc_demo() -> tuple[Target, list[Finding]]:
    target = Target(
        platform="gpu-cc",
        gpu_attestation_report="report.json",
        gpu_verifier_policy="policy.json",
        gpu_cc_mode="devtools",
        gpu_kbs_policy="kbs.json",
        gpu_model_bucket="model-weights-demo",
        gpu_launch_config="launch.json",
    )

    att = analyze_attestation_report(_DEMO_REPORT)
    rim = analyze_rim_pinning(_DEMO_POLICY, _DEMO_REPORT)
    cert = analyze_cert_policy(_DEMO_POLICY)
    mode = analyze_cc_mode("devtools")
    ready = analyze_key_release_policy(_DEMO_KBS)
    decrypt = analyze_decrypt_location(_DEMO_KBS)
    vram = analyze_vram_encryption(_DEMO_REPORT)
    dma = analyze_dma_session(_DEMO_REPORT)
    launch = analyze_launch_mutability(_DEMO_LAUNCH)
    cvm = analyze_cvm_binding(_DEMO_REPORT)
    sigv = analyze_signature_verification(_DEMO_POLICY)
    reatt = analyze_reattestation(_DEMO_POLICY)
    failopen = analyze_fail_closed(_DEMO_POLICY)
    keyh = analyze_key_hygiene(_DEMO_KBS)

    # Simulate a wide-open model bucket: every injection-shaped canary write lands.
    probe = probe_surface(ObjectStoreSurface(put_fn=lambda name: None)).as_evidence()

    findings = [
        Finding(
            check_id="GPUCC-ATT-01",
            title="GPU attestation report asserts a trusted state",
            status=Status.FAIL,
            severity=Severity.CRITICAL,
            summary="GPU attestation report does not assert a trusted state: "
            + "; ".join(att["issues"]) + ".",
            remediation="Collect the report from a CC-On production GPU.",
            evidence=att,
        ),
        Finding(
            check_id="GPUCC-RIM-01",
            title="Verification pins RIM golden measurements (VBIOS/firmware/driver)",
            status=Status.FAIL,
            severity=Severity.HIGH,
            summary="Verification does not pin the golden RIM measurements: "
            + "; ".join(rim["issues"]) + ".",
            remediation="Pin VBIOS/GSP-firmware/driver golden measurements in the verifier policy.",
            evidence=rim,
        ),
        Finding(
            check_id="GPUCC-CERT-01",
            title="Device certificate chain is validated to the NVIDIA root of trust",
            status=Status.FAIL,
            severity=Severity.HIGH,
            summary="Device cert chain is not validated to NVIDIA's RoT: "
            + "; ".join(cert["issues"]) + ".",
            remediation="Enable full cert-chain validation to the NVIDIA Device Identity CA.",
            evidence=cert,
        ),
        Finding(
            check_id="GPUCC-MODE-01",
            title="GPU is in CC-On mode, not CC-DevTools or CC-Off",
            status=Status.FAIL,
            severity=Severity.CRITICAL,
            summary="GPU is not in production Confidential Computing mode: "
            + "; ".join(mode["issues"]) + ".",
            remediation="Run the GPU in CC-On, never DevTools, for production workloads.",
            evidence=mode,
        ),
        Finding(
            check_id="GPUCC-READY-01",
            title="Workload attests before trusting the GPU (attestation-bound key release)",
            status=Status.FAIL,
            severity=Severity.CRITICAL,
            summary="GPU is trusted before attestation is verified: "
            + "; ".join(ready["issues"]) + ".",
            remediation="Verify attestation before ready-state ON; bind key release to it.",
            evidence=ready,
        ),
        Finding(
            check_id="GPUCC-MODEL-01",
            title="Model/weights bootstrap store rejects injection-shaped object writes",
            status=Status.FAIL,
            severity=Severity.HIGH,
            summary=(
                f"Model store accepted {len(probe['vulnerable'])}/{probe['tested']} "
                f"injection-shaped object writes across classes: "
                f"{', '.join(probe['vulnerable_classes'])}. A loader that joins these names "
                f"onto a local path without sanitizing gets attacker weights (boot-time "
                f"model poisoning)."
            ),
            remediation="Scope model-store writes to the attested identity; sanitize names.",
            evidence=probe,
        ),
        Finding(
            check_id="GPUCC-DECRYPT-01",
            title="Model/data decryption occurs inside the TEE, not untrusted host RAM",
            status=Status.FAIL,
            severity=Severity.HIGH,
            summary="Decryption is not confined to the TEE: " + "; ".join(decrypt["issues"]) + ".",
            remediation="Release the DEK into the attested TEE and decrypt weights on-GPU/in-CVM.",
            evidence=decrypt,
        ),
        Finding(
            check_id="GPUCC-VRAM-01",
            title="Hardware VRAM encryption is in effect",
            status=Status.FAIL,
            severity=Severity.HIGH,
            summary="VRAM encryption is not active: " + "; ".join(vram["issues"]) + ".",
            remediation="Run in CC-On so hardware VRAM encryption is enforced.",
            evidence=vram,
        ),
        Finding(
            check_id="GPUCC-DMA-01",
            title="CPU<->GPU DMA is encrypted over an SPDM secure session",
            status=Status.FAIL,
            severity=Severity.HIGH,
            summary="CPU<->GPU traffic is not fully protected: " + "; ".join(dma["issues"]) + ".",
            remediation="Run in CC-On to establish the SPDM secure session.",
            evidence=dma,
        ),
        Finding(
            check_id="GPUCC-VMM-META-01",
            title="The untrusted host cannot mutate the CVM/GPU launch configuration",
            status=Status.FAIL,
            severity=Severity.CRITICAL,
            summary="The CVM/GPU launch is mutable by the untrusted host: "
            + "; ".join(launch["issues"]) + ".",
            remediation="Pin the launch measurement; scope launch changes to admins only.",
            evidence=launch,
        ),
        Finding(
            check_id="GPUCC-CVM-01",
            title="GPU is attached to a verified Confidential VM (TDX/SEV-SNP)",
            status=Status.FAIL,
            severity=Severity.HIGH,
            summary="The CPU-side confidential VM is incomplete: " + "; ".join(cvm["issues"]) + ".",
            remediation="Run the GPU inside a verified, non-debug TDX/SEV-SNP CVM.",
            evidence=cvm,
        ),
        Finding(
            check_id="GPUCC-SIGVERIFY-01",
            title="The attestation report signature is cryptographically verified",
            status=Status.FAIL,
            severity=Severity.CRITICAL,
            summary="Report signature is not verified: " + "; ".join(sigv["issues"]) + ".",
            remediation="Cryptographically verify the report signature before trusting any claim.",
            evidence=sigv,
        ),
        Finding(
            check_id="GPUCC-REATTEST-01",
            title="Attestation is continuous, not one-shot (post-attest drift is caught)",
            status=Status.FAIL,
            severity=Severity.HIGH,
            summary="Attestation is not continuous: " + "; ".join(reatt["issues"]) + ".",
            remediation="Re-attest periodically and on GPU state change.",
            evidence=reatt,
        ),
        Finding(
            check_id="GPUCC-FAILOPEN-01",
            title="The verifier fails closed when attestation can't be checked",
            status=Status.FAIL,
            severity=Severity.HIGH,
            summary="The verifier fails open: " + "; ".join(failopen["issues"]) + ".",
            remediation="Fail closed: deny key/data release on any attestation error or outage.",
            evidence=failopen,
        ),
        Finding(
            check_id="GPUCC-KEY-01",
            title="Model/data key and workload identity are not an attestation bypass",
            status=Status.FAIL,
            severity=Severity.CRITICAL,
            summary="The key/identity is an attestation bypass: " + "; ".join(keyh["issues"]) + ".",
            remediation="KBS-release + rotate the DEK; drop SA keys; scope impersonation.",
            evidence=keyh,
        ),
    ]

    return target, findings
